import Header from "./Header"
import "../styles/globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head/>
      <body className="border-4 border-red-400 p-2 w-full">
        <Header/>
        {children}</body>
    </html>
  )
}
